package org.nolhtaced.desktop.enumerators;

public enum EAppForm {
    CATEGORY_FORM,
    CUSTOMER_FORM,
    CUSTOMER_BICYCLES_FORM,
    EMPLOYEE_FORM,
    PRODUCT_FORM,
    REPAIR_FORM,
    SALES_FORM,
    SERVICE_FORM,
    TRANSACTION_DETAIL_FORM,
    TRANSACTION_STATE_FORM,
    USER_FORM
}
